apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
nameSuffix: -qa
patchesStrategicMerge:
  - ordering-db-credentials-patch.yaml
  - ordering-service-deployment-patch.yaml