# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: inventory-policy
# spec:
#   podSelector:
#     matchLabels:
#       app: inventory-service
#   policyTypes:
#   - Egress
#   egress:
#   - to:
#     - ipBlock:
#         cidr: <tenant-a-db-ip>/32
#     ports:
#     - protocol: TCP
#       port: 1433