apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
nameSuffix: -dev
patchesStrategicMerge:
  - inventory-db-credentials-patch.yaml
  - inventory-service-deployment-patch.yaml