apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
nameSuffix: -dev
patches: 
  - path: inventory-db-credentials-patch.yaml
    target:
      kind: Secret
      name: inventory-db-credentials