apiVersion: v1
kind: ConfigMap
metadata:
  name: ordering-flyway-scripts
data:
  V1__create_orders_table.sql: |
    CREATE TABLE Orders (
        Id INT IDENTITY(1,1) PRIMARY KEY,
        BookId INT NOT NULL,
        Quantity INT NOT NULL,
        CustomerId INT NOT NULL,
        CreatedAt DATETIME DEFAULT GETDATE()
    );