apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
nameSuffix: -dev
patchesStrategicMerge:
  - recommendation-db-credentials-patch.yaml
  # - recommendation-service-deployment-patch.yaml